/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_properties_brand = pgEnum("enum_properties_brand", [
  "madeirabook",
  "madeiraoasis",
  "both",
]);
export const enum_properties_status = pgEnum("enum_properties_status", [
  "draft",
  "published",
  "archived",
]);
export const enum_bookings_status = pgEnum("enum_bookings_status", [
  "pending",
  "paid",
  "cancelled",
  "refunded",
]);
export const enum_bookings_source = pgEnum("enum_bookings_source", [
  "booking_channel",
  "direct",
  "owner_manual",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    resetPasswordRequestedAt: timestamp("reset_password_requested_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const amenities = pgTable(
  "amenities",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    icon: varchar("icon"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("amenities_updated_at_idx").on(columns.updatedAt),
    index("amenities_created_at_idx").on(columns.createdAt),
  ],
);

export const locations = pgTable(
  "locations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: jsonb("description"),
    geoCoordinates_lat: numeric("geo_coordinates_lat", {
      mode: "number",
    }).notNull(),
    geoCoordinates_lng: numeric("geo_coordinates_lng", {
      mode: "number",
    }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("locations_slug_idx").on(columns.slug),
    index("locations_updated_at_idx").on(columns.updatedAt),
    index("locations_created_at_idx").on(columns.createdAt),
  ],
);

export const properties_media = pgTable(
  "properties_media",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("properties_media_order_idx").on(columns._order),
    index("properties_media_parent_id_idx").on(columns._parentID),
    index("properties_media_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [properties.id],
      name: "properties_media_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const properties_audio_tracks = pgTable(
  "properties_audio_tracks",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    audio: integer("audio_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("properties_audio_tracks_order_idx").on(columns._order),
    index("properties_audio_tracks_parent_id_idx").on(columns._parentID),
    index("properties_audio_tracks_audio_idx").on(columns.audio),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [properties.id],
      name: "properties_audio_tracks_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const properties = pgTable(
  "properties",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    brand: enum_properties_brand("brand").notNull().default("madeirabook"),
    pmsPropertyId: varchar("pms_property_id"),
    pricePerNight: numeric("price_per_night", { mode: "number" }).notNull(),
    cleaningFee: numeric("cleaning_fee", { mode: "number" }),
    location: integer("location_id").references(() => locations.id, {
      onDelete: "set null",
    }),
    featured: boolean("featured").default(false),
    status: enum_properties_status("status").notNull().default("draft"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("properties_slug_idx").on(columns.slug),
    index("properties_location_idx").on(columns.location),
    index("properties_updated_at_idx").on(columns.updatedAt),
    index("properties_created_at_idx").on(columns.createdAt),
  ],
);

export const properties_rels = pgTable(
  "properties_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    amenitiesID: integer("amenities_id"),
  },
  (columns) => [
    index("properties_rels_order_idx").on(columns.order),
    index("properties_rels_parent_idx").on(columns.parent),
    index("properties_rels_path_idx").on(columns.path),
    index("properties_rels_amenities_id_idx").on(columns.amenitiesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [properties.id],
      name: "properties_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["amenitiesID"]],
      foreignColumns: [amenities.id],
      name: "properties_rels_amenities_fk",
    }).onDelete("cascade"),
  ],
);

export const bookings = pgTable(
  "bookings",
  {
    id: serial("id").primaryKey(),
    property: integer("property_id")
      .notNull()
      .references(() => properties.id, {
        onDelete: "set null",
      }),
    guestTelegramId: numeric("guest_telegram_id", { mode: "number" }),
    guestEmail: varchar("guest_email"),
    checkIn: timestamp("check_in", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    checkOut: timestamp("check_out", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    status: enum_bookings_status("status").notNull().default("pending"),
    source: enum_bookings_source("source").notNull().default("direct"),
    totalPrice: numeric("total_price", { mode: "number" }).notNull(),
    platformFeeCents: numeric("platform_fee_cents", {
      mode: "number",
    }).notNull(),
    smoobuBookingId: varchar("smoobu_booking_id"),
    stripeSessionId: varchar("stripe_session_id"),
    stripePaymentIntent: varchar("stripe_payment_intent"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("bookings_property_idx").on(columns.property),
    index("bookings_guest_telegram_id_idx").on(columns.guestTelegramId),
    index("bookings_status_idx").on(columns.status),
    index("bookings_smoobu_booking_id_idx").on(columns.smoobuBookingId),
    uniqueIndex("bookings_stripe_session_id_idx").on(columns.stripeSessionId),
    index("bookings_updated_at_idx").on(columns.updatedAt),
    index("bookings_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    amenitiesID: integer("amenities_id"),
    locationsID: integer("locations_id"),
    propertiesID: integer("properties_id"),
    bookingsID: integer("bookings_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_amenities_id_idx").on(
      columns.amenitiesID,
    ),
    index("payload_locked_documents_rels_locations_id_idx").on(
      columns.locationsID,
    ),
    index("payload_locked_documents_rels_properties_id_idx").on(
      columns.propertiesID,
    ),
    index("payload_locked_documents_rels_bookings_id_idx").on(
      columns.bookingsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["amenitiesID"]],
      foreignColumns: [amenities.id],
      name: "payload_locked_documents_rels_amenities_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["locationsID"]],
      foreignColumns: [locations.id],
      name: "payload_locked_documents_rels_locations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["propertiesID"]],
      foreignColumns: [properties.id],
      name: "payload_locked_documents_rels_properties_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["bookingsID"]],
      foreignColumns: [bookings.id],
      name: "payload_locked_documents_rels_bookings_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const cookie_policy = pgTable("cookie_policy", {
  id: serial("id").primaryKey(),
  title: varchar("title"),
  content: varchar("content"),
  last_updated: timestamp("last_updated", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const privacy_policy = pgTable("privacy_policy", {
  id: serial("id").primaryKey(),
  title: varchar("title"),
  content: varchar("content"),
  last_updated: timestamp("last_updated", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const terms_of_service = pgTable("terms_of_service", {
  id: serial("id").primaryKey(),
  title: varchar("title"),
  content: varchar("content"),
  last_updated: timestamp("last_updated", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const legal_info = pgTable("legal_info", {
  id: serial("id").primaryKey(),
  livro_de_reclamacoes_title: varchar("livro_de_reclamacoes_title"),
  livro_de_reclamacoes_description: varchar("livro_de_reclamacoes_description"),
  livro_de_reclamacoes_link: varchar("livro_de_reclamacoes_link"),
  cacram_ral_title: varchar("cacram_ral_title"),
  cacram_ral_description: varchar("cacram_ral_description"),
  cacram_ral_link: varchar("cacram_ral_link"),
  cacram_ral_contact_email: varchar("cacram_ral_contact_email"),
  cacram_ral_contact_phone: varchar("cacram_ral_contact_phone"),
  company_info_company_name: varchar("company_info_company_name"),
  company_info_nif: varchar("company_info_nif"),
  company_info_address: varchar("company_info_address"),
  company_info_email: varchar("company_info_email"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_amenities = relations(amenities, () => ({}));
export const relations_locations = relations(locations, () => ({}));
export const relations_properties_media = relations(
  properties_media,
  ({ one }) => ({
    _parentID: one(properties, {
      fields: [properties_media._parentID],
      references: [properties.id],
      relationName: "media",
    }),
    image: one(media, {
      fields: [properties_media.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_properties_audio_tracks = relations(
  properties_audio_tracks,
  ({ one }) => ({
    _parentID: one(properties, {
      fields: [properties_audio_tracks._parentID],
      references: [properties.id],
      relationName: "audioTracks",
    }),
    audio: one(media, {
      fields: [properties_audio_tracks.audio],
      references: [media.id],
      relationName: "audio",
    }),
  }),
);
export const relations_properties_rels = relations(
  properties_rels,
  ({ one }) => ({
    parent: one(properties, {
      fields: [properties_rels.parent],
      references: [properties.id],
      relationName: "_rels",
    }),
    amenitiesID: one(amenities, {
      fields: [properties_rels.amenitiesID],
      references: [amenities.id],
      relationName: "amenities",
    }),
  }),
);
export const relations_properties = relations(properties, ({ one, many }) => ({
  location: one(locations, {
    fields: [properties.location],
    references: [locations.id],
    relationName: "location",
  }),
  media: many(properties_media, {
    relationName: "media",
  }),
  audioTracks: many(properties_audio_tracks, {
    relationName: "audioTracks",
  }),
  _rels: many(properties_rels, {
    relationName: "_rels",
  }),
}));
export const relations_bookings = relations(bookings, ({ one }) => ({
  property: one(properties, {
    fields: [bookings.property],
    references: [properties.id],
    relationName: "property",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    amenitiesID: one(amenities, {
      fields: [payload_locked_documents_rels.amenitiesID],
      references: [amenities.id],
      relationName: "amenities",
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: "locations",
    }),
    propertiesID: one(properties, {
      fields: [payload_locked_documents_rels.propertiesID],
      references: [properties.id],
      relationName: "properties",
    }),
    bookingsID: one(bookings, {
      fields: [payload_locked_documents_rels.bookingsID],
      references: [bookings.id],
      relationName: "bookings",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_cookie_policy = relations(cookie_policy, () => ({}));
export const relations_privacy_policy = relations(privacy_policy, () => ({}));
export const relations_terms_of_service = relations(
  terms_of_service,
  () => ({}),
);
export const relations_legal_info = relations(legal_info, () => ({}));

type DatabaseSchema = {
  enum_properties_brand: typeof enum_properties_brand;
  enum_properties_status: typeof enum_properties_status;
  enum_bookings_status: typeof enum_bookings_status;
  enum_bookings_source: typeof enum_bookings_source;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  amenities: typeof amenities;
  locations: typeof locations;
  properties_media: typeof properties_media;
  properties_audio_tracks: typeof properties_audio_tracks;
  properties: typeof properties;
  properties_rels: typeof properties_rels;
  bookings: typeof bookings;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  cookie_policy: typeof cookie_policy;
  privacy_policy: typeof privacy_policy;
  terms_of_service: typeof terms_of_service;
  legal_info: typeof legal_info;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_amenities: typeof relations_amenities;
  relations_locations: typeof relations_locations;
  relations_properties_media: typeof relations_properties_media;
  relations_properties_audio_tracks: typeof relations_properties_audio_tracks;
  relations_properties_rels: typeof relations_properties_rels;
  relations_properties: typeof relations_properties;
  relations_bookings: typeof relations_bookings;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_cookie_policy: typeof relations_cookie_policy;
  relations_privacy_policy: typeof relations_privacy_policy;
  relations_terms_of_service: typeof relations_terms_of_service;
  relations_legal_info: typeof relations_legal_info;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
